apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: flux-prod

images:
- name: index.docker.io/sshjavi/go-gitops-api
  newName: index.docker.io/sshjavi/go-gitops-api
  newTag: 26178f1e3692f73ce306db7a1d617911df3f1624
